targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "aarch64-unknown-linux-gnu" },
  { triple = "x86_64-unknown-linux-musl" },
  { triple = "aarch64-apple-darwin" },
  { triple = "x86_64-apple-darwin" },
  { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
severity-threshold = "medium"
git-fetch-with-cli = true

[licenses]
unlicensed = "allow"
copyleft = "allow"
default = "allow"

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "all"
workspace-default-features = "deny"
external-default-features = "allow"
deny = [
  # We never want to use openssl
  { name = "openssl-sys" },
]
