//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub mod column_type;
pub mod enums;

pub mod episode;
pub mod genre;
pub mod movie;
pub mod season;
pub mod subscription;
pub mod task;
pub mod tv;
