name: Rust

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          components: rustfmt, clippy

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: cargo test
